apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kdimgjk8b-go 
  janus-idp.io/tekton: kdimgjk8b-go
  backstage.io/kubernetes-id: kdimgjk8b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kdimgjk8b-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  