apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kdimgjk8b-go-gitops
  description: This is GitOps manifest for kdimgjk8b-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kdimgjk8b-go
    backstage.io/kubernetes-id: kdimgjk8b-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kdimgjk8b-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kdimgjk8b-go
